"""The release-state gate, so public prose cannot keep saying nothing has shipped.

Four passages still told readers the name on PyPI was an empty placeholder long after
0.1.0 was on PyPI. A denylist is cruder than a parser and catches exactly that.
"""

from __future__ import annotations

import re
from pathlib import Path

import sandboxio

ROOT = Path(__file__).resolve().parent.parent

# docs/spec/ is normative and out of scope; docs/errors/ is generated by
# scripts/gen_error_catalog.py.
SKIP_DIRS = {ROOT / "docs" / "spec", ROOT / "docs" / "errors"}

# The placeholder version that held the name before 0.1.0 shipped.
UNRELEASED_VERSION = "0.0.0"

# Lower-cased, matched against whitespace-normalised prose. Each phrase has to be
# unsayable about a released project: a gate that fails on ordinary prose gets
# worked around, which is the one thing this repo does not do with a red gate.
DENIED = (
    "pre-alpha",
    "nothing is released",
    "nothing released",
    "not yet released",
    "not yet published",
    "no version is suitable for any use",
    "when we release",
    "`0.0.0` placeholder",
    "does not yet get you a library",
)

WHITESPACE = re.compile(r"\s+")


def _pages() -> list[Path]:
    pages = [ROOT / "README.md"]
    pages += [
        p
        for p in sorted((ROOT / "docs").rglob("*.md"))
        if not any(d in p.parents for d in SKIP_DIRS)
    ]
    return pages


def test_public_prose_does_not_claim_an_unreleased_project() -> None:
    assert sandboxio.__version__ != UNRELEASED_VERSION, (
        "update this gate for a pre-release tree"
    )

    hits = [
        f"{p.relative_to(ROOT)}: {phrase!r}"
        for p in _pages()
        for phrase in DENIED
        if phrase in WHITESPACE.sub(" ", p.read_text("utf-8")).lower()
    ]
    assert not hits, (
        f"sandboxio {sandboxio.__version__} is released, but this prose says otherwise:\n"
        + "\n".join(f"  {h}" for h in hits)
        + "\n\nRewrite the passage to describe what shipped, then regenerate "
        "docs/llms-full.txt with scripts/gen_llms_full.py."
    )
