#!/usr/bin/env python3
"""Concatenate the user-facing docs into docs/llms-full.txt, or --check that it is current.

Order follows docs/llms.txt. Stdlib only; the pages are the source, the file is derived.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "llms.txt"
OUT = DOCS / "llms-full.txt"
LINK = re.compile(r"^- \[[^\]]+\]\(([^)]+)\)", re.MULTILINE)
STAMP = "<!-- Generated by scripts/gen_llms_full.py from the pages listed in llms.txt. -->"


def pages() -> list[Path]:
    seen: list[Path] = []
    for target in LINK.findall(INDEX.read_text(encoding="utf-8")):
        path = (DOCS / target).resolve()
        if path.suffix == ".md" and path not in seen:
            seen.append(path)
    return seen


def render() -> str:
    parts = [STAMP, ""]
    parts.append(INDEX.read_text(encoding="utf-8").rstrip())
    for path in pages():
        rel = path.relative_to(ROOT).as_posix()
        parts += ["", "", "=" * 78, f"# FILE: {rel}", "=" * 78, ""]
        parts.append(path.read_text(encoding="utf-8").rstrip())
    return "\n".join(parts) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(
                f"{OUT.relative_to(ROOT)} is stale; run scripts/gen_llms_full.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(ROOT)} is current ({len(pages())} pages)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(pages())} pages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
